"""my migration16 

Revision ID: 08437860f721
Revises: 346f1051c48e
Create Date: 2024-07-03 11:59:56.540116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08437860f721'
down_revision: Union[str, None] = '346f1051c48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_email', table_name='otp')
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.create_index('ix_otp_email', 'otp', ['email'], unique=False)
    # ### end Alembic commands ###
