"""My migration8

Revision ID: 67638ce529da
Revises: c7db445e7e9f
Create Date: 2024-07-01 18:28:54.652021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67638ce529da'
down_revision: Union[str, None] = 'c7db445e7e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'disease',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'disease',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
