"""My migration3

Revision ID: 9d6e29f2d397
Revises: d70594184b05
Create Date: 2024-06-27 15:36:53.945481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6e29f2d397'
down_revision: Union[str, None] = 'd70594184b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'lname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('lname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
