"""New Migration2

Revision ID: d70594184b05
Revises: e5f1f28fa60e
Create Date: 2024-06-27 15:32:52.959102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70594184b05'
down_revision: Union[str, None] = 'e5f1f28fa60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('lname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'lname')
    # ### end Alembic commands ###
