"""My migration6

Revision ID: d7094f718d54
Revises: 92cdae74a29e
Create Date: 2024-06-28 10:38:07.949169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7094f718d54'
down_revision: Union[str, None] = '92cdae74a29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
