"""new migration13

Revision ID: f17554950b04
Revises: 66b2427afc88
Create Date: 2024-07-02 12:37:56.886182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17554950b04'
down_revision: Union[str, None] = '66b2427afc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_active')
    # ### end Alembic commands ###
